### ISSUE TITLE
CSRF Meta Tag

### ISSUE THREAD

**Issue by bhk1019** [alwaysconfused1/bootcamp#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

https://github.com/alwaysconfused1/bootcamp/blob/257ff1d0bf5a51d498162cecf04450311a18dcbc/app/views/layouts/application.html.erb#L11

**Comment by BigPhatNerd** [comment]
I think I'm good. That was cool. Thanks for helping me figure that out. I'm pretty sure I have it in the wrong place on my portfolio code as well. I cant wait to check it out.
